/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_labeltile_free: (a: number, b: number) => void;
export const __wbg_vectortilerenderer_free: (a: number, b: number) => void;
export const labeltile_placed: (a: number) => number;
export const labeltile_takePixels: (a: number, b: number) => void;
export const vectortilerenderer_addGlyphs: (a: number, b: number, c: number, d: number) => void;
export const vectortilerenderer_addSprite: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const vectortilerenderer_attributions: (a: number, b: number) => void;
export const vectortilerenderer_diagnostics: (a: number, b: number) => void;
export const vectortilerenderer_drawLabels: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => void;
export const vectortilerenderer_glyphsUrlTemplate: (a: number, b: number) => void;
export const vectortilerenderer_hasGlyphs: (a: number) => number;
export const vectortilerenderer_neededGlyphs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const vectortilerenderer_needsCpu: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const vectortilerenderer_needsSprite: (a: number) => number;
export const vectortilerenderer_new: (a: number, b: number, c: number, d: number) => void;
export const vectortilerenderer_plan: (a: number, b: number, c: number, d: number, e: number) => void;
export const vectortilerenderer_queryFeatures: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number) => void;
export const vectortilerenderer_render: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const vectortilerenderer_renderGeometry: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const vectortilerenderer_renderLabels: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const vectortilerenderer_renderLabelsPng: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => void;
export const vectortilerenderer_setSourceTiles: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const vectortilerenderer_setStyle: (a: number, b: number, c: number, d: number) => void;
export const vectortilerenderer_spriteUrls: (a: number, b: number, c: number) => void;
export const vectortilerenderer_unresolvedSources: (a: number, b: number) => void;
export const vectortilerenderer_unsupportedLayerTypes: (a: number, b: number) => void;
export const vectortilerenderer_defaultTileSize: () => number;
export const start: () => void;
export const __wbindgen_export: (a: number, b: number, c: number) => void;
export const __wbindgen_export2: (a: number, b: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
